### ISSUE TITLE
Extend Terraform SQL Database/Server module with basic performance monitoring

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/geh-terraform-modules#23]
Extend the Terraform module with alerts that monitors basic usage.

- Types we need to monitor
  - CPU
  - Memory
  - Storage
- Set up action group for alerts that points to an email (Teams Channel)

**Comment by kerbou** [comment]
Closing issue - monitoring should be part of DoD/acceptance criteria on features/Epics going forward
